<a href="https://colab.research.google.com/github/Herawisp/Scientific_Computing_LAB/blob/main/SC-Sesi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Catatan

In [ ]:
import time
print(time.ctime())

Thu Feb  6 04:39:53 2025


Data Types, Variable and Assignment

In [ ]:
a = "hello"
b = 20
c = 30.0
d = ["Apple", "Berry"]

print(a, b, c, d)

hello 20 30.0 ['Apple', 'Berry']


In [ ]:
a = int(1)
b = int(2.8)
c = int("3")
d = str(20)

print(a, b, c, d)

1 2 3 20


Concat String

In [ ]:
a = "Hello"
b = " World"
c = a + b
print(c)

Hello World


In [ ]:
a = "Hello World"
print(a[1])
print(len(a))

e
11


Slicing

In [ ]:
b = "BINUS Univ"
print(b[2:5])

c = "BINUS Univ"
print(c[:5])

d = "BINUS Univ"
print(d[2:])

NUS
BINUS
NUS Univ


In [ ]:
a = "Hello"
print(a.upper())

b + " World"
print(b.lower())

c = "Hello"
print(a.replace("H", "J"))

d = "Hello World"
print(d.split(" "))

HELLO
binus univ
Jello
['Hello', 'World']


In [ ]:
nama = "sam"
x = 19
string = "Hello namaku {}, umurku {}"
print(string.format(nama, x))

Hello namaku sam, umurku 19


In [ ]:
nama = "Grace"
for i in enumerate(nama):
  print(i)

(0, 'G')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


Function, If-Else Statements

In [ ]:
def perbandingan (a, b):
  if a > b:
    print("a lebih besar dari b")
  elif a == b:
    print("a sama dengan b")
  else:
    print("a lebih kecil dari b")

In [ ]:
perbandingan(4, 8)

a lebih kecil dari b


Looping

In [ ]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


In [ ]:
i = 1
for i in range(2, 6):
  print(i)

2
3
4
5


In [ ]:
for i in range(2, 41):
    if i % 2 == 0:
      print(i, "adalah genap")
    else:
      print(i, "adalah ganjil")

2 adalah genap
3 adalah ganjil
4 adalah genap
5 adalah ganjil
6 adalah genap
7 adalah ganjil
8 adalah genap
9 adalah ganjil
10 adalah genap
11 adalah ganjil
12 adalah genap
13 adalah ganjil
14 adalah genap
15 adalah ganjil
16 adalah genap
17 adalah ganjil
18 adalah genap
19 adalah ganjil
20 adalah genap
21 adalah ganjil
22 adalah genap
23 adalah ganjil
24 adalah genap
25 adalah ganjil
26 adalah genap
27 adalah ganjil
28 adalah genap
29 adalah ganjil
30 adalah genap
31 adalah ganjil
32 adalah genap
33 adalah ganjil
34 adalah genap
35 adalah ganjil
36 adalah genap
37 adalah ganjil
38 adalah genap
39 adalah ganjil
40 adalah genap


Numpy Arrays

In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [3, 6, 7]])
x

array([[1, 2, 3],
       [3, 6, 7]])

In [ ]:
y = np.array([[8, 2, 9], [3, 5, 7]])
y

array([[8, 2, 9],
       [3, 5, 7]])

In [ ]:
print(x+y)

[[ 9  4 12]
 [ 6 11 14]]


In [ ]:
data = np.array ([10, 9, 8, 7, 5, 6])
print("Rata-rata:", np.mean(data))
print("Maksimum:", np.max(data))
print("Minimum:", np.min(data))
print("Standar Deviasi:", np.std(data))

# Modul 1

Login dengan sistem password

In [16]:
username = input("Masukkan username anda : ")

while True:
  password = input("Masukkan password anda : ")
  if password == "Admin123": break
  print("Password salah, coba lagi.")

print("Login Berhasil, Selamat datang", username)

Masukkan username anda : Ailie
Masukkan password anda : Admin123
Login Berhasil, Selamat datang Ailie


Meminta data mahasiswa

In [17]:
nama_siswa = input("Masukkan nama siswa : ")

while True:
  try:
    uas = float(input("Masukkan nilai UAS : "))
    if 0 <= uas <= 100: break
    print("Nilai harus diantara 0 - 100, coba lagi.")
  except ValueError:
    print("Nilai harus berupa angka, coba lagi.")

while True:
  try:
    uts = float(input("Masukkan nilai UTS : "))
    if 0 <= uts <= 100: break
    print("Nilai harus diantara 0 - 100, coba lagi.")
  except ValueError:
    print("Nilai harus berupa angka, coba lagi.")

while True:
  try:
    assignment = float(input("Masukkan nilai UTS : "))
    if 0 <= assignment <= 100: break
    print("Nilai harus diantara 0 - 100, coba lagi.")
  except ValueError:
    print("Nilai harus berupa angka, coba lagi.")

Masukkan nama siswa : Reynard
Masukkan nilai UAS : 78
Masukkan nilai UTS : 100
Masukkan nilai UTS : 98


Menghitung Nilai Akhir

In [18]:
def calculate(uas, uts, asg):
  return (uas * 0.5) + (uts * 0.3) + (asg * 0.2)

def grading(total):
  if 90 <= total <= 100: return "A"
  elif 85 <= total <= 89: return "A-"
  elif 80 <= total <= 84: return "B+"
  elif 75 <= total <= 79: return "B"
  elif 70 <= total <= 74: return "B-"
  elif 65 <= total <= 69: return "C"
  elif 60 <= total <= 64: return "D"
  elif 11 <= total <= 59: return "E"
  else: return "F"

final_score = calculate(uas, uts, assignment)
grade = grading(final_score)

Tampilan Hasil Akhir

In [19]:
print("====================================================")
print("Hasil perolehan nilai", nama_siswa)
print("Final Score:", final_score)
print("Grade:", grade)


Hasil perolehan nilai Reynard
Final Score: 88.6
Grade: A-
